site_name: ciphergeist
repo_url: https://github.com/BR4GR/ciphergeist
site_url: https://BR4GR.github.io/ciphergeist
site_description: riddles and stuff
site_author: Benjamin
edit_uri: edit/main/docs/
repo_name: BR4GR/ciphergeist
copyright: Maintained by <a href="https://BR4GR.com">BR4GR</a>.

nav:
  - Home: index.md
  - Cryptopals:
    - Set 1:
      - 1. Convert hex to base64: cryptopals/set1_basics/1-convert-hex-to-base64.md
      - 2. Fixed XOR: cryptopals/set1_basics/2-fixed-XOR.md
      - 3. Single-byte XOR cipher: cryptopals/set1_basics/3-single-byte-XOR-cipher.md
      - 4. Detect single-character XOR: cryptopals/set1_basics/4-detect-single-character-XOR.md
      - 5. Implement repeating-key XOR: cryptopals/set1_basics/5-implement-repeating-key-XOR.md
  - SHC Challenges:
    - Crypto:
      - CRY-205: shc/crypto/cry-205.md
      - Farm Life: shc/crypto/farm-life.md
      - HSB: shc/crypto/hsb.md
      - Office Encryption: shc/crypto/office-encryption.md
      - Really Secure Application: shc/crypto/really-secure-application.md
      - XOXO: shc/crypto/xoxo.md
    - Web:
      - Calculator: shc/web/calculator.md
  - Reference: reference/

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/ciphergeist"]
theme:
  name: material
  logo: assets/hero.png
  favicon: assets/hero.png
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/solid/ghost

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BR4GR/ciphergeist
    # - icon: fontawesome/brands/python
    #   link: https://pypi.org/project/ciphergeist
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
