site_name: ciphergeist
repo_url: https://github.com/BR4GR/ciphergeist
site_url: https://BR4GR.github.io/ciphergeist
site_description: riddles and stuff
site_author: Benjamin
edit_uri: edit/main/docs/
repo_name: BR4GR/ciphergeist
copyright: Maintained by <a href="https://BR4GR.com">BR4GR</a>.

nav:
  - Home: index.md
  - Modules: modules.md
  - Cryptopals:
    - Set 1:
      - 1. Convert hex to base64: cryptopals/set1_basics/1_convert_hex_to_base64.md
      - 2. Fixed XOR: cryptopals/set1_basics/2_fixed_XOR.md
      - 3. Single-byte XOR cipher: cryptopals/set1_basics/3_single_byte_XOR_cipher.md
      - 4. Detect single-character XOR: cryptopals/set1_basics/4_detect_single_character_XOR.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/ciphergeist"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BR4GR/ciphergeist
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ciphergeist

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
